### ISSUE TITLE
Change editor to use spaces instead of tabs, and remove trailing whitespace

### ISSUE THREAD

**Issue by jpsember** [tsember/freight-portal#1]
See [this link](http://stackoverflow.com/questions/1043433/how-to-auto-remove-trailing-whitespace-in-eclipse).

Everyone working on a project should use the same settings for these options (my recommendations):

+ indentation: spaces only
+ indentation size:2
+ tab size:2
+ trim trailing whitespace on every save

**Comment by jpsember** [comment]
Eclipse has a setting to automatically remove trailing whitespace:


> 1. Removing whitespace from the entire file being edited:
> Preferences -> Java -> Editors -> Save Actions -> check "Perform the selected actions on save" -> check "Additional actions" -> click "Configure.." -> go to "Code organizing" tab -> check "Remove trailing whitespace" -> select "All lines".

**Comment by tsember** [comment]
I have adjusted my Eclipse preferences to automatically remove trailing whitespace, and i believe i have set my tab indentations and tab size to 2. We will see what happens the next time i commit...

**Comment by jpsember** [comment]
@tsember , have a look at this... you should go to the Eclipse settings and 'import' the xml file I added to the scripts directory.
![screen shot 2016-05-07 at 4 05 30 pm](https://cloud.githubusercontent.com/assets/4098788/15095110/92dd4d88-146d-11e6-88d7-9117df695625.jpeg)

**Comment by tsember** [comment]
okay i did this, and the instant i applied it in Eclipse, some indent of a
few lines changed in a class file so i think this is working...

**Comment by jpsember** [comment]
Seems to be working
