### ISSUE TITLE
Rate Request Desk may not find any potential carriers for a shipment

### ISSUE THREAD

**Issue by tsember** [tsember/freight-portal#100]
in which case it should tell the customer something.

**Comment by Stargate-Freight-Portal** [comment]
If no carriers found this should then go to the help desk at least at the start.

Thanks and have a great day

Bruce Hendriks
Leverage Logistics
604-468-8484

On Jun 11, 2016, at 2:49 PM, tsember <notifications@github.com<mailto:notifications@github.com>> wrote:


in which case it should tell the customer something.

-
