### ISSUE TITLE
Request object implementation of joda does not work

### ISSUE THREAD

**Issue by tsember** [tsember/freight-portal#103]
I believe the problem is that the function getTimestamp() which i want to return a double does not work properly. Which is either that the json functions aren't ready to deal with doubles, or i don't know how to properly work with doubles.

In any case, the real job is to get Requests to look like Shipment objects and deal with timestamps the same way everywhere, so i kind of think this error is not worth spending any time on.

but it must be noted.

**Comment by jpsember** [comment]
To retrieve a timestamp from a Request (or Shipment), use the static method `RequestUtils.timestamp(obj)`.  In fact, if you're using RequestUtils, you should probably add it as a static import, so the above can be shortened to just `timestamp(obj)`.

See RequestTest.java for some sample code.
