### ISSUE TITLE
Generating test shipments needs to be its own app outside of RateRequestDesk

### ISSUE THREAD

**Issue by tsember** [tsember/freight-portal#123]
Explain here?

**Comment by tsember** [comment]
the shipment generator needs to be its own app, and not be inside the ShipmentDesk

**Comment by jpsember** [comment]
It's part of the shipment package right now, which I think is ok.  While it is only for test purposes, I think it's ok where it is... we'd need to create a test package that is accessible to any class that might want to access a ShipmentStore, but let's not do that right now. 

Feel free to ignore the class for now.
