### ISSUE TITLE
command line arguments

### ISSUE THREAD

**Issue by tsember** [tsember/freight-portal#14]
implement the concept of hidden default config file in the user's home directory that can be over-ridden by a command line argument specifying "-c"

**Comment by jpsember-adszio** [comment]
I looked into simple libraries for command line parsing for Java programs, and there ISN'T ONE.  They get really ridiculous, so you should just write your own utility method that parses command line arguments.  Things to keep in mind:

- [ ] Some arguments will be optional, so you should return a default value if none is given
- [ ] You should report an error if an argument such as "-c <path>" is given what looks like another option (i.e. starts with "-") in place of the "<path>"
- [ ] A common feature is that a single dash precedes one or more single-character options, e.g., "-cq" is treated the same as "-c -q", and that some options have both long and short forms ("-c" == "--config").  This is a low priority feature.
- [ ] A nice way to do this might be to construct a json map containing the arguments and their default values, then as you parse the actual arguments given by the user, change the map's values accordingly; then return the map to the main program.

PS These checkboxes are entered by typing a dash followed by a space followed by [], and are a nice GitHub feature.

**Comment by tsember** [comment]
okay thanks for the input.

my feelings are at this point that the config file can get as complicated
as we want, but it's gonna be in JSON, and all you get to do is specify a
different one on the command line. Not gonna spend too much time on it. I
know we are gonna want to put debug options on the command line, but again,
not so important now, everything will be in debug mode at the start.

but i like how we are operating, and GitHub is going to be invaluable as an
issue tracker. And everything will be an issue.

**Comment by tsember** [comment]
New command line argument class tested and works as expected...
