### ISSUE TITLE
initializeDesk function better look the same for all 4 desks

### ISSUE THREAD

**Issue by tsember** [tsember/freight-portal#143]
I don't want to share the code, but they better open things exactly the same way.

and maybe some desks don't open everything... which is fine.

**Comment by tsember** [comment]
ApprovalDesk uses: mShipmentStore = ShipmentStore.buildInput(workspace());

and PortalDesk uses: mShipmentStore = ShipmentStore.buildOutput(workspace());

They are both operating on the single Shipment database, neither is creating any shipments. They cannot both be correct. I suspect this means ApprovalDesk is wrong, because QuoteDesk and ShipmentDesk who also use the single Shipment database use buildOutput.

i suspect unit testing will throw more light on the solution here...

**Comment by jpsember** [comment]
Everyone but the RequestDesk should be using the output ShipmentStore, I think... if you use the wrong one in an isolated unit test, it might not complain, but you will have problems when trying to 'connect' them together in a more thorough use case

**Comment by tsember** [comment]
Yes. I wish there was only one ShipmentStore, and I believe this will become apparent when the Web Browser creates shipments, because all their data comes from the customer typing stuff in on a web page. And then the ShipmentDesk will simply be triggered by something, and not "read" any shipments in from anywhere...
