### ISSUE TITLE
we need a policy on what the Sender name is on Emails the Stargate Freight Portal generates...

### ISSUE THREAD

**Issue by tsember** [tsember/freight-portal#145]

**Comment by tsember** [comment]
so far, we generate the following kinds of emails in the 4 desks that comprise the Stargate Freight Portal

- internal emails to the help desk when something is wrong
- emails to customers about their shipments
- emails to carriers requesting quotes

I think the solution is:

- internal emails we have the name of the desk as the sender
- emails to customers probably all have the same sender name
- emails to carriers probably all have the same sender name, but not necessarily same as the customer name

this isn't urgent, but looking for comments from you guys...?

**Comment by tsember** [comment]
@Stargate-Freight-Portal

**Comment by Stargate-Freight-Portal** [comment]
I agree with your solution.  I don't think the emails to customers and carriers needs to have a different sender names unless that is an internal need that is necessary so we can differentiate between the two.

________________________________

**Comment by jpsember-adszio** [comment]
When we have a functional email interface, it will be associated with an email address, eg admin@stargatefp.com or some such.  This is the sender regardless of the recipient.  For example, when something goes wrong, we send an email from the system to one or more of us, timsember@gmail etc.

On a related note we will want to have emails support multiple recipients.

**Comment by jpsember-adszio** [comment]
The source of a problem email, such as which desk is sending it, will have to be inferred from the subject or body of the message (down the road I guess we could have multiple internal email addresses)
