### ISSUE TITLE
PortalDeskTest is not getting command line arguments in to PortalDesk

### ISSUE THREAD

**Issue by tsember** [tsember/freight-portal#147]

**Comment by tsember** [comment]
the problem is addArgs.

it doesn't work in ShipmentDesk either...

**Comment by tsember** [comment]
i have added tons of debug. Problem as far as i can see is the only the very first command line argument "makes it thru" to the actual app that runs.

inside file AppTestCase, inside functions runApp and addArgs, whatever is in mArg and args looks just like it is supposed to.

inside the actual ShipmentDesk program, if you dump the command line arguments, the first one, work directory, makes it over. The others don't, and if you don't initialize the arguments with addCommandLineArguments nothing else gets specified.

**Comment by tsember** [comment]
In the example below, note that work directory name makes it "thru" however the application is being called, but max_inactive_iterations does not. It becomes 3 because in the code inside ShipmentDesk i initialize it to 3. changed one line of code on my version. But the 1 that should be coming over to change that never makes it.

I think the bug is going to be that only the first command line argument makes it thru all the code that is calling an application from the Unit Tests. But i don't understand that code well enough to tinker with it.

Running com.tsember.shipmentDesk.ShipmentDeskTest
| INFO: 
| INFO: ------------ starting test: testFixedPriceRoute                                                                    {ShipmentDeskTest:TOOZIT}
| INFO: TJS in addArgs, before doing anything mArgs are : 
| INFO: []
| INFO: TJS in addArgs, args are : 
| INFO: w/work-directory /Users/jeff/Desktop/_freight_test_tmp_/testFixedPriceRoute
| INFO: end of args
| INFO: TJS in addArgs, afterwards, mArgs are : 
| INFO: [w/work-directory, /Users/jeff/Desktop/_freight_test_tmp_/testFixedPriceRoute]
| INFO: TJS in addArgs, before doing anything mArgs are : 
| INFO: [w/work-directory, /Users/jeff/Desktop/_freight_test_tmp_/testFixedPriceRoute]
| INFO: TJS in addArgs, args are : 
| INFO: i/max-inactive-iterations 1
| INFO: end of args
| INFO: TJS in addArgs, afterwards, mArgs are : 
| INFO: [w/work-directory, /Users/jeff/Desktop/_freight_test_tmp_/testFixedPriceRoute, i/max-inactive-iterations, 1]
| INFO: inside runApp in AppTestCase, mArgs are : 
| INFO: [w/work-directory, /Users/jeff/Desktop/_freight_test_tmp_/testFixedPriceRoute, i/max-inactive-iterations, 1]
| INFO: 
| INFO: execute                                                                                                                {ShipmentDesk:HEHNIX}
| INFO: inside initializeDesk in the ShipmentDesk, cmdLineArgs look like:
| INFO: 
| INFO:     { "L/log-config-file" : "",
| INFO:           "c/config-file" : "",
| INFO:              "g/generate" : false,
| INFO:       "i/max-inactive-iterations" : 
| INFO:                             3,
| INFO:          "l/log-file-dir" : "",
| INFO:        "w/work-directory" : "/Users/jeff/Desktop/_freight_test_tmp_/testFixedPriceRoute"
| INFO:     }
| INFO: ShipmentDesk has started up...

**Comment by jpsember** [comment]
Looking into this now...

**Comment by jpsember** [comment]
This is now fixed; you can close when you're satisfied with it
