### ISSUE TITLE
Install HomeBrew ('brew') on Tim's computer if not already

### ISSUE THREAD

**Issue by jpsember** [tsember/freight-portal#15]
It can be downloaded from [here](http://brew.sh/)

To see if you've already installed it:
```
> brew -v
Homebrew 0.9.5 (git revision 8003c; last commit 2015-08-27)
```

**Comment by tsember** [comment]
brew -v 
Homebrew 0.9.5

but it doesn't say anything else. So i claim it's installed on here, we see what happens when i try to use it.
