### ISSUE TITLE
add Eclipse run time configuration to git tree

### ISSUE THREAD

**Issue by tsember** [tsember/freight-portal#20]
so that the "standard" way of running programs can be distributed to other users, and documented and saved...

**Comment by jpsember** [comment]
As discussed, we will require that developers have maven (as the underlying command-line build tool), but their choice of IDE is up to them, and we shouldn't pollute the repository with Eclipse-specific project files.

**Comment by jpsember** [comment]
We now have a script that builds Eclipse project files from the maven specification, so that's certainly sufficient.
