### ISSUE TITLE
implement Shipment object log concept

### ISSUE THREAD

**Issue by tsember** [tsember/freight-portal#21]
We need to track what happens to a shipment as it passes thru the freight-portal project.

right now, these objects are passed around as JSON files that become JSmaps inside a process.

first cut will be to add a big string to the Shipment object, that each process will add to as it does something to the Shipment. In the future this probably becomes something more useful like an array of strings. 

first cut will just say that "BareBonesDesk operated on this object".
second cut will say "BareBonesDesk operated on this object at <timestamp>".

**Comment by tsember** [comment]
second cut will say "BareBonedDesk processed this object at 14:05 April 3, 2016"

**Comment by jpsember** [comment]
There are established logging frameworks that will do this job nicely, writing to log files both on disk and echoing to the console.  This is better than storing the information with the Shipment object itself.  Let me look into how to add the logging support.

**Comment by jpsember** [comment]
You may need to have eclipse add additional elements to the build path to correspond to the maven settings (this step is not yet automatic, and will have to be repeated whenever we add dependencies to the project such as log4j)

**Comment by jpsember** [comment]
Logging is working well.  The log library also supports the ability to have particular classes write to different log files... that's not implemented by us yet.
