### ISSUE TITLE
Assign unique ids to shipments, as they are processed, if they have none

### ISSUE THREAD

**Issue by jpsember** [tsember/freight-portal#28]
It's either that, or we have to assume the shipment ids have already been assigned as they are written to the input directory.

**Comment by tsember** [comment]
So far, i have been thinking that the shipments are going to be JSON files in the input directory, the name of the file will be it's shipment id, and the front end (whatever that is) will be managing these ids. They will start at some base number and be incremented by one each time.

but philosophically i have no problem if we decide that the RateRequestDesk, (which is what BareBonesDesk will become) decides that it should take over this task, and do just what you said, create unique ids. Hopefully starting at a base number and incrementing by one so i don't go crazy when i test this. But the front end better create unique file names, it doesn't know how many requests BareBonesDesk has processed already. And as soon as somebody has to worry about unique file names, they may as well assign the id's...

**Comment by jpsember** [comment]
Let's assume that whoever is writing them into the 'input' directory is responsible for giving them unique ids.
