### ISSUE TITLE
Eclipse 'imports' 

### ISSUE THREAD

**Issue by jpsember** [tsember/freight-portal#31]
A problem I'm trying to avoid is having us inadvertently changing the order/number of import statements for no good reason.  This makes git (and github) show changes where there really aren't any.

Here's a screenshot of my Eclipse settings... I recommend you do a 'Restore Defaults' and then change the two numbers from 99 to 3 as shown.  Then we'll keep an eye on subsequent commits.

![screen shot 2016-05-08 at 9 44 24 am](https://cloud.githubusercontent.com/assets/4098788/15099105/ab20f93c-1501-11e6-8184-97c464691556.jpeg)

**Comment by tsember** [comment]
i think this is resolved...
