### ISSUE TITLE
Add sample class demonstrating marshalling / serialization

### ISSUE THREAD

**Issue by jpsember** [tsember/freight-portal#4]
Wikipedia articles of interest:

https://en.wikipedia.org/wiki/Serialization

https://en.wikipedia.org/wiki/Marshalling_(computer_science)

**Comment by jpsember** [comment]
I assigned this to you only so you get notified of my comments and related commits.

**Comment by jpsember** [comment]
The 'Shipment2' class you can see has a public interface (the public methods) that don't expose the fact that it's being represented internally by a json map.  This way the representation could change down the road if necessary.

**Comment by tsember** [comment]
ok, you have given me lots to work with, thanks!    and the assigning and
commenting is all working well!

**Comment by jpsember-adszio** [comment]
The shipment and shipmentstore classes intentionally have very abstract interfaces so that it is easy to change how the objects are represented in memory, or how they are persisted to disk, ie, to switch to a database down the road.
