### ISSUE TITLE
Construct 'working' directory for testing

### ISSUE THREAD

**Issue by jpsember** [tsember/freight-portal#41]
This will be a directory that lies within the directory tree of the git repository, and will contain the configuration files and sample data (at least for development).  This is to avoid polluting our various file systems with miscellaneous files and to ensure consistent test results.

To start with a 'fresh' work directory, the application can be run with the `-Z` option.   If running via Rake, then this is done by:
```
rake delete_work_dir
```
For convenience, you may want to set an alias, i.e.
```
alias rc="rake delete_work_dir"
```
then from Terminal you can just type `rc`.  Alternatively, make the `delete_work_dir` the default Rake task (see Rakefile.rb).

**Comment by jpsember** [comment]
- [ ] We should decide if the 'RateDeliveryDesk' should have its own 'work' directory, or if it should share some files with the 'BareBonesDesk'.

**Comment by tsember** [comment]
at 3pm on Sunday afternoon, I believe i have committed everything necessary that if anyone does a git pull they should be running in "my" test environment, with the following:

a rudimentary geography database consisting of 2 regions each with 2 cities in them.

a rudimentary carrier database consisting of 2 carriers, one who serves the I-5 corridor, and 1 who ships containers across the North Pacific.

an input directory of 3 shipments. 1 is along the I5 corridor, 1 across the Pacific, 1 is not served by any existing carrier.
