### ISSUE TITLE
Figure out how to organize various apps

### ISSUE THREAD

**Issue by jpsember** [tsember/freight-portal#55]
The BareBonesDesk for example is a separate app from the RateDeliveryDesk app (I think), whereas
the build system wants to build and package a jar file for a single app.

- [ ] Is it reasonable to actually have all the apps packaged together in a single jar file, and have a command line argument choose which one is to run?  This might be simplest and quickest in the short term; it's suboptimal because unnecessary code is being packaged up where only a single app is required.
- [ ] Or... should we have a separate submodule for each app (Maven supports this, and I've been doing that with my other project)?

**Comment by tsember** [comment]
I think of RateDeliveryDesk as a separate app from BareBonesDesk. 

so i think they should all be separate. I think of CarrierDB as a separate app, i think of GeoDB as a separate app, etc.

and I would like to be able to test each one individually, and stop and start individually. running the BareBonesDesk does not depend on a RateDeliveryDesk running. And for example, when we implement a carrierDB, it is independent of everything else.
