### ISSUE TITLE
Eclipse gets confused a lot, necessitating a clean of the project

### ISSUE THREAD

**Issue by jpsember** [tsember/freight-portal#56]
Not sure why... always has this effect:

![screen shot 2016-05-18 at 5 55 35 pm](https://cloud.githubusercontent.com/assets/4098788/15379411/cc38ae30-1d21-11e6-9e1f-e0706f4cc331.jpeg)

**Comment by tsember** [comment]
let me see if this happens for me...

**Comment by tsember** [comment]
i had the same sorts of errors, the logTest stuff and OurTestCase can't be figured out by Eclipse. and a clean in Eclipse solved it.
