### ISSUE TITLE
Carrier objects need integer ids

### ISSUE THREAD

**Issue by tsember** [tsember/freight-portal#62]
we are going to need to look up things by carrier, and i would much rather use an integer than a string for database lookups.

Whoever makes up the database of Carriers will assign these numbers, by the time they get in to the rest of the Freight Portal system the number has been assigned.

**Comment by jpsember** [comment]
Who owns the Carrier database?  Is it ours?  If so, we should write a 'CarrierService' class that manages the assignment of unique ids.

If you give me some idea of what it needs to do I can handle this.
