### ISSUE TITLE
Shipments need an ISF filing before they leave port

### ISSUE THREAD

**Issue by Stargate-Freight-Portal** [tsember/freight-portal#70]
this is really a test that Bruce can create an issue at his house

**Comment by jpsember** [comment]
WELCOME ABOARD

Did they tell you at orientation that it's $15 for an elevator pass?  You can pay me if you like and I'll pass it on to management

**Comment by Stargate-Freight-Portal** [comment]
Thank you, it is an honor and a privilege to be on board.  I believe $15.00 for an elevator pass is money well spent as I can barely move anymore unless I am chasing a soccer ball.

________________________________
