### ISSUE TITLE
implement timestamps properly

### ISSUE THREAD

**Issue by tsember** [tsember/freight-portal#92]

**Comment by tsember** [comment]
Rate Request desk must timestamp every shipment it sends to Carriers for quotes. It must also timestamp every quote it sends to Customers for approval.

Rate Delivery desk must timestamp every quote it sends to Customers for approval.

Portal Manager uses the timestamps on shipments to decide if they have expired because no carrier responded. Portal Manager uses the timestamps on quotes to decide if a shipment expires because the Customer did not approve a quote in time.

Customer Manager doesn't need to worry about timestamps right now, Portal Manager is handling whether customers respond in time. Customer Manager will simply not find the referenced shipment if the Portal Manager expired it.

**Comment by tsember** [comment]
and the timestamps are really attached to the shipment, the shipment status indicates what the timestamp refers to. I probably will make separate timestamps because of this fact. No overloading variables in these times of cheap disk space.

**Comment by jpsember** [comment]
Can we add a timestamp field to each appropriate object, e.g. Shipment, Quote, etc., at the time they are constructed?  In addition it's probably a good idea to make each of these objects immutable (if practical); it simplifies things.  When we need to change the state of a shipment, for instance, we instead ask a shipment object to construct a new version of itself with an updated state.

**Comment by tsember** [comment]
both ideas make sense to me.

**Comment by jpsember** [comment]
I think we've got the necessary support in place now; see the Shipment and Request utility classes and unit tests for examples.
