### ISSUE TITLE
Add support for protocol buffers

### ISSUE THREAD

**Issue by jpsember** [tsember/freight-portal#94]
This is Google's library for serializing structured data, and is an alternative to our method of storing object state internally within JSMaps.

https://developers.google.com/protocol-buffers/

https://developers.google.com/protocol-buffers/docs/javatutorial

It can be confusing to use these at first, but I've been using them for quite some time so I think I can make it fairly painless (I didn't want to introduce these earlier as you had enough on your plate).

How it works:
+ We describe the structure of the data (objects) we want to represent in a text file; see `sample.proto`
+ We run this through the protoc compiler.  It generates actual Java source files to manipulate Java objects according to the definitions in sample.proto.
+ The compilation step can be automated, as we've done in the Rakefile.rb.  I'll add it to the test task as well.

- [ ] Add script or something to post-process the generated protobuf models to get rid of the compile warnings

-----------------------------

- [x] What happens on Tim's machine when he types in the Terminal: `protoc --version` ?
- [x] Now try: `brew install protobuf`

**Comment by tsember** [comment]
work_template> protoc --version
-bash: protoc: command not found

**Comment by jpsember-adszio** [comment]
Try:

brew install protoc

**Comment by tsember** [comment]
mygit> brew install protoc
Error: No available formula for protoc 
Searching taps...

and i did not have joda on my machine. i got it from the web but i really don't like what i had to do to get it to work. i found a single jar file, and i also found a zip file, but in both cases i had to go make a directory  with way too many levels,something like:

/Users/jeff/.m2/repository/joda-.../joda-.../2.8.2 

and this was a lot of work to get Eclipse to decide there were no errors. But i could run the project. But there's no way i should be installing it like this...

**Comment by jpsember** [comment]
You shouldn't need to do that manually.  In future, when there's a problem similar to this, let me know / file an issue report.  Because it's much better to figure out why it's not working... it's supposed to be an automatic process.

**Comment by tsember** [comment]
looks like it worked:

mygit> brew install protobuf
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/protobuf-2.5.0.maveric
######################################################################## 100.0%
==> Pouring protobuf-2.5.0.mavericks.bottle.tar.gz
==> Caveats
Editor support and examples have been installed to:
  /usr/local/Cellar/protobuf/2.5.0/share/doc/protobuf
==> Summary
🍺  /usr/local/Cellar/protobuf/2.5.0: 75 files, 6.2M
