### ISSUE TITLE
Figure out how to properly install joda on my machine

### ISSUE THREAD

**Issue by tsember** [tsember/freight-portal#95]
We need to figure out how to do this in a general sense:

1. When adding new dependencies to the project (pom.xml), when building from the command line (mvn package, or via Rake), it should automatically download the dependencies... that's the whole point
1. We should be able to use the meclipse.rb script to rebuild the eclipse project, and it should configure the build path as well so no manual farting around is required (though closing and refreshing the project from within Eclipse may be required)

**Comment by jpsember** [comment]
Steps for Tim:

- [ ] From within the freight project root directory, type: `mv ~/.m2 ~/Desktop/_moved_m2.dir`
