### ISSUE TITLE
Refactor to eliminate ShipmentStore (use ShipmentDatabase instead)

### ISSUE THREAD

**Issue by jpsember** [tsember/freight-portal#97]

**Comment by jpsember** [comment]
- [ ] What is the distinction between 'input_directory' and 'shipment_db_directory' (see RateRequestDesk)?

**Comment by tsember** [comment]
input_directory is where the Rate Request Desk sees shipment requests come in from the user. They are dealt with and deleted.

shipment_db_directory is where the local Shipment database is stored, used by all the Desks/Managers

**Comment by tsember** [comment]
and i am trying to be consistent with naming. db_directories are all our local databases.

output_directories are going to disappear, we either send emails or manipulate local databases

**Comment by jpsember** [comment]
Ok thanks

**Comment by tsember** [comment]
and backup directories i am not sure about, i leave them in but not sure if we really need them...
